module: ml_project.model_selection
class: GridSearchCV
params:
  est_module: ml_project.pipeline
  est_class: Pipeline
  est_params:
    - module: ml_project.models.preprocessing
      class: Flatten
    - module: sklearn.preprocessing
      class: StandardScaler
    - module: ml_project.models.preprocessing
      class: Normalization
    - module: ml_project.models.feature_selection
      class: PrincipleComponentAnalysis
#      params:
#        n_components: 200
    - module: ml_project.models.regression
      class: RidgeRegression

  param_grid:
    PrincipleComponentAnalysis__n_components:
      - 140
      - 160
      - 180
      - 200
    RidgeRegression__alpha:
      - 0.1
      - 1
      - 4
      - 8
      - 12
  cv:
    module: sklearn.model_selection
    class: KFold
    params:
      n_splits: 3
      shuffle: True
      random_state: 37
