module: ml_project.model_selection
class: GridSearchCV
params:
  est_module: ml_project.pipeline
  est_class: Pipeline
  est_params:

    - module: ml_project.models.preprocessing
      class: CropCubeHist
      params:
        nbins: 22
        rmin: 1
        rmax: 1300
        d: 10

    - module: sklearn.feature_selection
      class: VarianceThreshold
      params:
        threshold: 0.0

    - module: sklearn.preprocessing
      class: Normalizer

    - module: ml_project.models.regression
      class: GaussianProcessRegression
      params:
        alpha: 0.0000001

  param_grid:
    CropCubeHist__nbins:
      - 20
      - 22
      - 24
      - 26

    CropCubeHist__rmax:
      - 1000
      - 1200
      - 1400
      - 1600

  cv:
    module: sklearn.model_selection
    class: KFold
    params:
      n_splits: 3
      shuffle: True
      random_state: 37
