module: ml_project.model_selection
class: GridSearchCV
params:
  est_module: ml_project.pipeline
  est_class: Pipeline
  est_params:

    - module: ml_project.models.preprocessing
      class: CropCubeHist
      params:
        rmin: 1
        d: 10

    - module: sklearn.feature_selection
      class: VarianceThreshold
      params:
        threshold: 0.0

    - module: sklearn.preprocessing
      class: Normalizer

    - module: ml_project.models.regression
      class: GaussianProcessRegression
      params:
        alpha: 0.0000001

  param_grid:
    CropCubeHist__nbins:
      - 28
      - 30
      - 32

    CropCubeHist__rmax:
      - 100
      - 3800
      - 4000
      - 4200

  cv:
    module: sklearn.model_selection
    class: KFold
    params:
      n_splits: 3
      shuffle: True
